name: Lyle Baer
favicon: null
layout_spectrum: 0.24597
typography_spectrum: 0.94362
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76727504-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7f94c5'
    - '#204da9'
    - '#8dffff'
    - '#367bd7'
  brandStrength: 0.49074662919156253
  lightness: 0.21774022979661822
  saturation: 0.7647504522465169
  rhythmicContrast: 0.32192736328579485
purpose: []
