name: Lyle Baer
favicon: null
layout_spectrum: 0.24597
typography_spectrum: 0.94362
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76727504-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#414360'
    - '#b5abaa'
    - '#c15c1d'
    - '#f29c1a'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
