name: Lyle Baer
favicon: null
layout_spectrum: 0.24597
typography_spectrum: 0.94362
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76727504-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eae4df'
    - '#888ea4'
    - '#16151d'
    - '#5a4448'
    - '#566d9c'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
