name: Lyle Baer
favicon: null
layout_spectrum: 0.24597
typography_spectrum: 0.94362
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76727504-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7ca7de'
    - '#1c221e'
    - '#a3c3eb'
    - '#f5f5f3'
    - '#484943'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
